### PR TITLE
Restructuring

### PR DESCRIPTION
**Pull request by chrisjbillington**
This PR restructures qtutils into the layout we're using for the other labscript-adjacent projects.

It moves most of the metadata out into `setup.cfg`, and uses `setuptools_scm` for build and dev versioning, and `importlib_metadata` for runtime versioning in the same way as the other projects.

It adds a `pyproject.toml` listing the build dependencies so that `pip install -e`, `pip wheel` etc know how to install the build dependencies.

The build dependencies are `PyQt5` and `PySide2`: the built icon `.py` files have been removed from the repository and are now generated during the build (by subclassing the setuptools `build_py` command, as opposed to the previous hacks we were doing).

A section for `setuptools-conda` in `setup.cfg` tells it that `PyQt5` is named differently and that it should look in `conda-forge` for `PySide2`:
```
[dist_conda]
conda_name_differences =
  PyQt5:pyqt

# Build requirement for the PySide2 icons resource file - pyside is only in conda-forge.
channels =
  conda-forge
```

This is only relevant during the build, which is when PyQt5 and PySide2 are needed for the resource-generation utilities that make the icon `.py` files. The Qt libraries aren't runtime dependencies.

Moved icon image files and `.qrc` file out of the package directory since they are not shipping with the package (sorry about that, that's what's going to make the diff for this useless - you should probably just clone it and look around if you want to see what is different!).

Removed `PY2` compatibility.

Removed `PyQt4` and `PySide` support.

Added our standard workflow for building an sdist, wheel and conda package, configured for a pure noarch package.

Added section to the readme explaining briefly how to use the `.qrc` file with Qt Designer.

Replaced references to bitbucket in copyright headers with the github URL.

Automatic package building looks to be working! The conda package (of which there is only once since it's a 'noarch' package)  is only 5MB so we are not at massive risk of using our 3GB limit by drowning in icons.

### CODE REVIEW

**Comment by philipstarkey** [comment]
This just removes PyQt4/PySide support for the conda packages right?

**Comment by chrisjbillington** [comment]
No, it removes them in general.

PyQt4 isn't installable from PyPI, but it looks like PySide might be. They're both end of life four years ago though.

**Comment by philipstarkey** [comment]
GitHub doesn't say any .py files were modified though? Is that a bug in the interface or did you not strip out the PyQt4 compatibility layer?

**Comment by chrisjbillington** [comment]
I did strip it out. I'm on mobile now but here at least GitHub doesn't show most changes - I guess it sorted those files to be after the icons so they don't make the cut.

But some of the changes are in separate commits: e.g. edd288fe

**Comment by chrisjbillington** [comment]
I'm going to sleep but I could prepare a diff that skips the icon renaming if you're interested.

**Comment by philipstarkey** [comment]
Yeah could be good - possibly even split into 2 PRs?

GitHub has a file filter interface on the files changed tab but it (a) doesn't seem to filter and (b) doesn't list all the file extensions in the PR (making it useless)

**Comment by chrisjbillington** [comment]
Cool I've rewritten history to not move the icons files in this PR. Icon-moving is now in #11.

Have to merge both to get something functional that can be tested.

**Comment by philipstarkey** [comment]
I assume we are tagging this with 3.0.0? Can we add a note to the readme (probably after the first sentence under the "summary" header) stating the PyQt4/PySide/Python 2.7 support can be found in qtutils >= 2.3.2

**Comment by chrisjbillington** [comment]
Yep, this will definitely have to be a major release.

> Can we add a note to the readme (probably after the first sentence under the "summary" header) stating the PyQt4/PySide/Python 2.7 support can be found in qtutils >= 2.3.2

Sure, I'll add it!

**Comment by chrisjbillington** [comment]
Note added:

```markdown
`qtutils` 3.0 dropped support for Python 2.7, PyQt4 and PySide. If you need to use these
platforms, you may use `qtutils` 2.3.2 or earlier.
```

**Comment by chrisjbillington** [comment]
Merge?

**Comment by philipstarkey** [comment]
Sure, go for it

**Pull request merged**
