### PR TITLE
Packaging changes for conda

### PR DESCRIPTION
**Pull request by chrisjbillington**
* Switch to setuptools and setuptools_scm, remove as a result no longer
  needed README.txt, MANIFEST.in, `package_data` from setup.py.
* Correct syntax error in README.md.
* Use `setuptools_conda` to generate conda packages.

Conda packages can be generated with `python setup.py conda_dist` from a conda environment with `setuptools_conda` installed.

The resulting conda packages work, though there's some rough edges. First is that by default no Qt wrapper is installed, as the package doesn't list any as dependencies. This might be unsolvable and it will simply have to be stated in docs that you'll have to install Qt bindings as well. The only other option is depending on specific bindings.

The other issue is that if built for all all platforms (win32, win64, linux32, linux64, osx64) and all supported Pythons (2.7, 3.6, 3.7) (3.8 not quite working yet), the resulting builds clock in at 700MB. Anaconda cloud free accounts are only 3 GB of storage, so this could be an issue - we can only fit four releases of `qtutils` before having to delete old ones! Of course we could get a paid account, though it looks like we have to contact them to ask about pricing and features, I can't seem to find published pricing.

Another option (and something we may want to do anyway) is drop PyQt4 and Python2 (and therefore PySide) support. That means much fewer icon resource files. We'd then only have PyQt5 and beta PySide2 (Qt for Python) support. Python 2 is EOL at the end of this month and PyQt4 has been EOL since 2015. This brings the total size of a release down to 178MB (though it will increase again once the conda ecosystem starts working with Python 3.8).

We could also not bother building for 32 bit Linux, that brings it down to 143MB per release.

### CODE REVIEW

**Comment by chrisjbillington** [comment]
Another potential option is to split the icons package into a separate package so that it does not update as frequently. Though having said that, a decent number of the updates to qtutils have been "add an icon"...

**Comment by chrisjbillington** [comment]
Ok, by not building conda packages for Python 2 or linux-32 (one still can, but it's not default), plus excluding unnecessary files from the conda packages (such as the icon PNG files, the icon `.py` files—`.pyc` alone are sufficient—and the `.pyc` files for bindings not compatible with whichever Python version the package is being built for), I get it down to 83MB per release (python 3.6, 3.7, and 3.8).

However, I have plans for high DPI icons that potentially could increase that 4x.

We could also make the "fugue" icons a separate package, since it does not need to change very often, so it won't matter if it is large. Custom icons could still live in qtutils. I think we're ok for now, but is something to think about when I get the hidpi icons working. When that happens, since we will have proper dependency tracking with conda packages, it will be seamless, there won't be any disruption to users if we make a change like that later instead of now.

**Comment by philipstarkey** [comment]
Splitting off fugue is probably the way to go eventually.

Can we still support older Python/PyQt on PyPI? That way those stuck on legacy code can still get new versions for as long as we manage to keep it compatible. Not saying we do this forever, but I suspect it will take a while after Python 2.7 EOL for people to actually move on.

**Comment by chrisjbillington** [comment]
Well we don't have to rip out support now, and yeah the source distribution will continue working on PyPI. We'll save a little bit of space dropping PyQt4 support from the conda packages (it's still there at the moment, but pyqt4 is not even in the conda repos anymore - not even for Python 2 seemingly! So it should go)

It will be annoying to maintain compatibility if there is any major work to be done in the future, but the only things I see on the horizon are high DPI icons and Qt6, which is scheduled for about one year from now.

It's true that people will take some time to move on from Python 2, but at the same time I think they'll be pretty content with not getting new features in libraries - they'll be used to it :p. I wonder if there are any good statistics on how people are still going strong on Python 2 - not sure how to read [these](https://anaconda.org/anaconda/python/files?sort=ndownloads&sort_order=desc) download numbers given that the most recent version of Python 3.7 supposedly has ten times more downloads than the second most recent one - surely conda has not become ten times more popular in the last three months. Maybe it's downloads in the last month or something.

**Comment by chrisjbillington** [comment]
It's down to 57MB after dropping Qt4 from the conda packages, so that's not bad at all.

I think I'll aim to split fugue off when I get the High DPI icons working. Fugue actually has source files availalble in double the resolution, but they have sort of "inverse artifacts" that are intentionally drawn blocky in order to create sharp diagonal lines when downscaled for the 16x16 size. Still trying to figure out if I can programmatically remove these, or how many hours it would take to do it manually and whether it counts as meditation if I do...

**Comment by philipstarkey** [comment]
My past experience with feeding the `readme.md` file into the long description has been that installations from the resulting `sdist` package fail because `readme.md` is not included.

I've generally hacked around this like [so](https://github.com/Monash-University-Physics-Astronomy/monashspa/blob/master/setup.py#L65)

**Comment by chrisjbillington** [comment]
README.md does appear to be in the .tar.gz with these changes - my understanding is that pyPI now accepts README.md, so no README.txt is needed (although this requires `long_description_content_type='text/markdown',` to render correctly on PyPI - I've just added that in a commit just now).

With these changes I've removed MANIFEST.in in favour of declaring `'setuptools_scm'` in the `setup_requires` list - this has the effect of ensuring everything under version control is automatically included in the sdist.

So I think it's ok as is - [works on test PyPI](https://test.pypi.org/project/qtutils/2.4.0.dev2/): and I can pip install it.

**Comment by chrisjbillington** [comment]
Superseded by #10

**Pull request closed without merging**
